// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjzkjqtbbsrjimlhlcjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqemtqcXRiYnNyamltbGhsY2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NjMwMTIsImV4cCI6MjA1NTUzOTAxMn0.w45m1pImZ1lyzqM1Y-NDxow4ftTDg4MiDQLS3XRgjEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);